"""
impact_report.py
----------------
Runs the optimiser against the greedy baseline across several problem sizes and
writes a pitch-ready impact report to `data/impact_report.md`.

Resolves the reporting half of issue #12 ("feature these quantified impact
numbers prominently on the pitch slides"). Reading figures off a dashboard by
eye is not citable and not reproducible; this produces the same numbers every
time from a stated seed, so a slide can quote them and anyone can re-run it.

Usage
=====
    python scripts/impact_report.py                       # synthetic sizes
    python scripts/impact_report.py --real-city           # cached Delhi roads
    python scripts/impact_report.py --sizes 10 20 40 --fleet 500

Every figure is signed. If the optimiser does worse on a measure, the report
says so — a result table that cannot show a loss is not evidence.
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from typing import List, Optional

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.graph_model import generate_synthetic_city_graph      # noqa: E402
from app.core.vrp_problem import generate_synthetic_vrp             # noqa: E402
from app.core.qpso_vrp import QPSOVRPOptimizer                      # noqa: E402
from app.core.classical_baselines_vrp import run_greedy_nn_vrp      # noqa: E402
from app.core.impact import (                                       # noqa: E402
    ASSUMPTIONS, compute_impact, project_to_city,
)


def _fmt(value: float, unit: str = "", digits: int = 1) -> str:
    """Signed, so a regression is visible rather than dressed up."""
    sign = "+" if value > 0 else ""
    return f"{sign}{value:,.{digits}f}{unit}"


def run_case(n_customers: int, n_nodes: int, seed: int, max_iter: int,
             n_particles: int, use_cache: bool = False):
    """Solve one instance with greedy and with QPSO, and measure the difference."""
    if use_cache:
        from app.core.cached_network import load_cached_network
        net = load_cached_network("delhi_central", congestion_seed=seed)
    else:
        net = generate_synthetic_city_graph(n_nodes=n_nodes, seed=seed)

    problem = generate_synthetic_vrp(
        net, n_customers=n_customers, depot=0, vehicle_capacity=80, seed=seed
    )

    started = time.time()
    baseline = run_greedy_nn_vrp(problem).best_solution
    optimised = QPSOVRPOptimizer(
        problem, n_particles=n_particles, max_iter=max_iter, seed=seed
    ).optimize().best_solution
    runtime = time.time() - started

    km_saved = baseline.total_distance - optimised.total_distance
    min_saved = baseline.total_time - optimised.total_time

    impact = compute_impact(km_saved, min_saved, deliveries=n_customers)
    return {
        "n_customers": n_customers,
        "vehicles": problem.n_vehicles,
        "baseline": baseline,
        "optimised": optimised,
        "impact": impact,
        "runtime_s": runtime,
    }


def build_report(cases: List[dict], fleet_size: int, real_city: bool) -> str:
    a = ASSUMPTIONS
    scenario = "real Delhi road network (Connaught Place)" if real_city else "synthetic city networks"

    lines: List[str] = []
    add = lines.append

    add("# Real-world impact of quantum-behaved route optimisation")
    add("")
    add(f"_Generated by `scripts/impact_report.py` on {time.strftime('%Y-%m-%d')} "
        f"against {scenario}. Re-run it to reproduce every figure below._")
    add("")
    add("Route optimisation is usually reported as a percentage against another "
        "algorithm, which tells you nothing about whether it matters. This "
        "converts the same results into fuel, emissions and driver time.")
    add("")

    # ---- headline ----
    # The largest instance, NOT the most flattering one. Picking whichever case
    # happens to show the best CO2 number and describing it as "the largest"
    # would be cherry-picking, which is the thing this report exists to avoid.
    best = max(cases, key=lambda c: c["n_customers"])
    bi = best["impact"]
    add("## The headline")
    add("")
    add(f"On the largest instance measured ({best['n_customers']} deliveries, "
        f"{best['vehicles']} vehicles), replacing ordinary nearest-stop dispatch "
        f"with our optimiser changes one day's operation by:")
    add("")
    add(f"- **{_fmt(bi.driver_hours_saved, ' hours')}** of driver time")
    add(f"- **{_fmt(bi.litres_saved, ' litres')}** of diesel")
    add(f"- **{_fmt(bi.kg_co2_saved, ' kg')}** of CO2")
    add("")
    add(f"Per 100 deliveries that is **{_fmt(bi.litres_per_100_deliveries, ' litres')}** "
        f"of fuel and **{_fmt(bi.kg_co2_per_100_deliveries, ' kg')}** of CO2.")
    add("")

    if bi.km_saved < 0 and bi.minutes_saved > 0:
        add("**Read that carefully: this is a trade, not a clean win.** The optimiser "
            f"drives {abs(bi.km_saved):,.1f} km further and burns "
            f"{abs(bi.litres_saved):,.1f} litres more fuel, in exchange for "
            f"{bi.driver_hours_saved:,.1f} hours of driver time. Whether that is "
            "worth it depends on what an operator values — driver wages and "
            "delivery promises, or fuel and emissions. We report both rather than "
            "the flattering one.")
        add("")
        # Only feasible runs count as evidence. A solution that breaks capacity
        # or time windows has not solved the problem, so its "saving" is not a
        # saving and must not be cited in support of the method.
        wins = [c for c in cases
                if c["impact"].km_saved > 0 and c["optimised"].feasible]
        if wins:
            add(f"On smaller instances the same optimiser does save distance "
                f"({', '.join(str(c['n_customers']) for c in wins)} deliveries below), "
                f"so the trade-off appears as the problem grows rather than being "
                f"inherent to the method.")
            add("")
    else:
        add("> A negative figure is not an error. Routing around congestion can mean "
            "driving further to arrive sooner; where that happens the distance and "
            "fuel numbers go negative while the time saving stays positive.")
        add("")

    # ---- per-size table ----
    add("## Measured results by problem size")
    add("")
    add("| Deliveries | Vehicles | Time saved | Distance saved | Fuel | CO2 | Feasible |")
    add("| ---: | ---: | ---: | ---: | ---: | ---: | :--- |")
    for c in cases:
        i = c["impact"]
        add(f"| {c['n_customers']} | {c['vehicles']} | "
            f"{_fmt(i.minutes_saved, ' min')} | {_fmt(i.km_saved, ' km')} | "
            f"{_fmt(i.litres_saved, ' L')} | {_fmt(i.kg_co2_saved, ' kg')} | "
            f"{'yes' if c['optimised'].feasible else 'NO'} |")
    add("")
    add("Time and distance are measured by the solver. Fuel and CO2 are derived "
        "from distance using the factors below.")
    add("")
    infeasible = [c for c in cases if not c["optimised"].feasible]
    if infeasible:
        add(f"⚠️ **{len(infeasible)} of {len(cases)} runs produced an infeasible "
            f"solution** ({', '.join(str(c['n_customers']) for c in infeasible)} "
            f"deliveries) — the route breaks a vehicle capacity or a customer time "
            f"window. Those rows are shown for completeness but should not be "
            f"quoted as savings: a plan that breaks a delivery promise has not "
            f"solved the problem.")
        add("")

    # ---- city scale ----
    add(f"## At city scale ({fleet_size} vehicles)")
    add("")
    add("**These are projections, not measurements.**")
    add("")
    add("| Deliveries per run | Annual driver hours | Annual fuel | Annual CO2 |")
    add("| ---: | ---: | ---: | ---: |")
    for c in cases:
        p = project_to_city(c["impact"], vehicles_in_run=c["vehicles"], fleet_size=fleet_size)
        add(f"| {c['n_customers']} | {_fmt(p.annual_driver_hours, ' h', 0)} | "
            f"{_fmt(p.annual_litres, ' L', 0)} | {_fmt(p.annual_tonnes_co2, ' t')} |")
    add("")
    add(f"_{project_to_city(cases[0]['impact'], cases[0]['vehicles'], fleet_size).caveat}_")
    add("")

    # ---- assumptions ----
    add("## Assumptions")
    add("")
    add(f"- **{a.km_per_litre:g} km per litre** — diesel light commercial vehicle on an "
        f"urban duty cycle. Highway figures for this class are 10-14 km/L; stop-start "
        f"delivery work is worse, so this is deliberately conservative.")
    add(f"- **{a.kg_co2_per_litre:g} kg CO2 per litre** — DEFRA/IPCC combustion factor "
        f"for diesel. Implies {a.kg_co2_per_km():.3f} kg CO2 per km.")
    add(f"- **{a.working_days_per_year} working days per year** for annual figures.")
    add("")
    add("Change any of these in `app/core/impact.py` and re-run; every number here "
        "derives from that one place.")
    add("")

    # ---- method ----
    add("## Method")
    add("")
    add("Each row solves the same delivery problem twice: once with greedy "
        "nearest-stop dispatch (what ordinary routing software does) and once "
        "with the quantum-behaved optimiser. Both are scored on the same "
        "network with the same traffic, and both must respect vehicle capacity "
        "and customer time windows. The difference between them is what is "
        "reported.")
    add("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the real-world impact report.")
    ap.add_argument("--sizes", type=int, nargs="+", default=[10, 20, 40],
                    help="customer counts to measure")
    ap.add_argument("--nodes", type=int, default=60, help="synthetic network size")
    ap.add_argument("--fleet", type=int, default=100, help="city fleet size for the projection")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--max-iter", type=int, default=150)
    ap.add_argument("--particles", type=int, default=50)
    ap.add_argument("--real-city", action="store_true",
                    help="use the cached Delhi road network instead of synthetic ones")
    ap.add_argument("--out", default="data/impact_report.md")
    args = ap.parse_args()

    cases = []
    for n in args.sizes:
        print(f"Solving {n} deliveries …", flush=True)
        try:
            case = run_case(n, args.nodes, args.seed, args.max_iter,
                            args.particles, use_cache=args.real_city)
        except Exception as exc:
            print(f"  skipped: {type(exc).__name__}: {exc}")
            continue
        i = case["impact"]
        print(f"  {_fmt(i.minutes_saved, ' min')}, {_fmt(i.km_saved, ' km')}, "
              f"{_fmt(i.kg_co2_saved, ' kg CO2')}  ({case['runtime_s']:.1f}s)")
        cases.append(case)

    if not cases:
        print("No instance solved — nothing to report.")
        return 1

    report = build_report(cases, args.fleet, args.real_city)
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(report)

    print(f"\nWrote {args.out} ({len(report.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
