"""
scripts/measure_swarm_contribution.py
--------------------------------------
Where does a memetic run's improvement come from: the swarm's own moves, or
local search?

Both QPSO + LS and PSO + LS call local_search.refine_best on the swarm's best
every 15 iterations and once more at the end. This script wraps that function
to log the global-best fitness going into and coming out of every call. Between
two calls only the swarm can change the global best, so a run's total
improvement, initial best (iteration 0) minus final best, splits exactly into

    swarm before local search   initial best - input to the first call
    local search                sum over calls of (input - output)
    swarm after local search    sum over consecutive calls of
                                (output of call k-1 - input to call k)

The script asserts that the three parts add up to the total.

Same instances, seeds and budget as scripts/run_ablations.py (sections C-E).
Writes data/swarm_contribution.md and data/swarm_contribution.json.

    python scripts/measure_swarm_contribution.py
"""

from __future__ import annotations

import argparse
import json
import os
import statistics
import sys
import time
from concurrent.futures import ProcessPoolExecutor

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(ROOT)
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

import app.core.classical_baselines_vrp as baselines  # noqa: E402
import app.core.local_search as ls  # noqa: E402
import app.core.qpso_vrp as qpso_mod  # noqa: E402
from run_ablations import N_PARTICLES, _instance  # noqa: E402

LABELS = {"qpso_ls": "QPSO + LS", "pso_ls": "PSO + LS"}


def _run(task):
    config, n, seed, max_iter = task
    calls = []
    real = ls.refine_best

    def logged(problem, best_sol, best_fit, passes):
        out = real(problem, best_sol, best_fit, passes)
        calls.append((best_fit, out[0].fitness if out is not None else best_fit))
        return out

    # Both optimisers bound refine_best at import; patch those names.
    qpso_mod.refine_best = logged
    baselines.refine_best = logged

    problem = _instance(n, 1, 150)
    if config == "qpso_ls":
        r = qpso_mod.QPSOVRPOptimizer(problem, n_particles=N_PARTICLES, max_iter=max_iter,
                                      seed=seed, use_local_search=True).optimize()
    else:
        r = baselines.run_standard_pso_vrp(problem, n_particles=N_PARTICLES, max_iter=max_iter,
                                           seed=seed, use_local_search=True)
    initial, final = r.convergence_curve[0], r.best_fitness

    swarm_before = initial - calls[0][0]
    local_search = sum(i - o for i, o in calls)
    swarm_after = sum(calls[k - 1][1] - calls[k][0] for k in range(1, len(calls)))
    improved = sum(1 for k in range(1, len(calls)) if calls[k][0] < calls[k - 1][1] - 1e-9)
    total = initial - final
    assert abs(swarm_before + local_search + swarm_after - total) <= 1e-6 * max(1.0, abs(total))

    return {"config": config, "n": n, "seed": seed, "initial": initial, "final": final,
            "swarm_before": swarm_before, "local_search": local_search, "swarm_after": swarm_after,
            "windows_swarm_improved": improved, "windows": len(calls) - 1}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--seeds", type=int, default=5)
    parser.add_argument("--sizes", type=int, nargs="+", default=[20, 40, 60, 80, 100])
    parser.add_argument("--max-iter", type=int, default=150)
    parser.add_argument("--workers", type=int, default=os.cpu_count() or 1)
    args = parser.parse_args()

    started = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    tasks = [(c, n, s, args.max_iter) for n in args.sizes for c in LABELS
             for s in range(1, args.seeds + 1)]
    with ProcessPoolExecutor(max_workers=args.workers) as pool:
        runs = list(pool.map(_run, tasks))

    with open("data/swarm_contribution.json", "w") as f:
        json.dump({"generated_at": started, "settings": vars(args), "runs": runs}, f, indent=2)
    print("  wrote data/swarm_contribution.json")

    md = [
        "# Where the improvement comes from: swarm or local search",
        "",
        f"_Generated by `scripts/measure_swarm_contribution.py` on {started[:10]} with "
        f"`--seeds {args.seeds} --max-iter {args.max_iter} --sizes {' '.join(map(str, args.sizes))}`. "
        "Every run is in `data/swarm_contribution.json`._",
        "",
        "Same instances, seeds and budget as `data/ablation_results.md` §C–E. A run's total "
        "improvement (best fitness at iteration 0 minus final fitness) splits exactly into what "
        "the swarm found before the first local-search call (iteration 15), what local search "
        "added, and what the swarm added between local-search calls afterwards. Shares are of "
        "the total improvement, summed over seeds.",
        "",
        "| Customers | Algorithm | Swarm, iterations 0–15 | Local search | Swarm, after iteration 15 "
        "| Windows where the swarm improved the best |",
        "|---|---|---|---|---|---|",
    ]
    for n in args.sizes:
        for config, label in LABELS.items():
            rs = [r for r in runs if r["n"] == n and r["config"] == config]
            tot = sum(r["initial"] - r["final"] for r in rs)
            share = lambda key: 100 * sum(r[key] for r in rs) / tot  # noqa: E731
            md.append(f"| {n} | {label} | {share('swarm_before'):.1f}% | {share('local_search'):.1f}% "
                      f"| {share('swarm_after'):.2f}% "
                      f"| {sum(r['windows_swarm_improved'] for r in rs)}/{sum(r['windows'] for r in rs)} |")

    allr = runs
    md += ["",
           f"Over all {len(allr)} runs, the swarm improved the global best in "
           f"{sum(r['windows_swarm_improved'] for r in allr)} of "
           f"{sum(r['windows'] for r in allr)} windows between local-search calls, adding "
           f"{sum(r['swarm_after'] for r in allr):.1f} fitness in total, against "
           f"{sum(r['local_search'] for r in allr):.1f} from local search. Median swarm gain "
           f"before the first call: {statistics.median(r['swarm_before'] for r in allr):.1f}; "
           f"it was zero in {sum(1 for r in allr if r['swarm_before'] <= 1e-9)} runs.",
           ""]
    with open("data/swarm_contribution.md", "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    print("  wrote data/swarm_contribution.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
